apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-monitor-timescaledb
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-storage
