apiVersion: v1
kind: Service
metadata:
  name: pg-monitor-timescaledb
  labels:
    app: pg-monitor-timescaledb
spec:
  ports:
  - nodePort: 30002
    port: 5432
    targetPort: 5432
    protocol: TCP
    name: pg-monitor-timescaledb
  selector:
    app: pg-monitor-timescaledb
  type: NodePort
