# https://blog.travis-ci.com/2017-10-26-running-kubernetes-on-travis-ci-with-minikube
# https://github.com/LiliC/travis-minikube
env:
  global:
    - CHANGE_MINIKUBE_NONE_USER=true
    - MINIKUBE_WANTUPDATENOTIFICATION=false
    - MINIKUBE_WANTREPORTERRORPROMPT=false
    - MINIKUBE_HOME=$HOME
    - CHANGE_MINIKUBE_NONE_USER=true
    - KUBECONFIG=$HOME/.kube/config
    - PGHOST=localhost
    - PGUSER=postgres
    - PGPASSWORD=pgpass
    - PGPORT=30002
    - KUBEVERSION=v1.17.0
    # 1.17.0 to 
    # https://kubernetes.io/docs/setup/release/notes/
    - MINIKUBEVERSION=v1.6.2
    #1.6.2 to 1.14.0
    # https://github.com/kubernetes/minikube/tags

jobs:
  include:
    - #stage: PostgreSQL 10
      name: "PostgreSQL 10 - TimescaleDB 1.5.1"
      env:
        - TSVERSION=1.5.1
        - PGVERSION=pg10
      language: bash
      services: docker
      sudo: required
      addons:
        apt:
          packages:
            - postgresql-client
            - perl
            - python3
            - python3-psycopg2
            - python3-daemon
      before_script:
        # Download kubectl, which is a requirement for using minikube.
        - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/$KUBEVERSION/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
        # Download minikube.
        - curl -Lo minikube https://storage.googleapis.com/minikube/releases/$MINIKUBEVERSION/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
        #- curl -Lo minikube https://storage.googleapis.com/minikube/releases/$MINIKUBEVERSION/minikube-linux-amd64 && chmod +x minikube && sudo install minikube-linux-amd64 /usr/local/bin/minikub && minikube kubectl -- get po -A
        - mkdir -p $HOME/.kube $HOME/.minikube
        - touch $KUBECONFIG
        - sudo minikube start --vm-driver=none --kubernetes-version=$KUBEVERSION
        - "sudo chown -R travis: /home/travis/.minikube/"
        # Add https://metacpan.org/pod/TAP::Parser::SourceHandler::pgTAP for pg_prove
        - cpanm --sudo TAP::Parser::SourceHandler::pgTAP
      script: 
        - ~/build/LloydAlbin/pg_monitor/internal_testing/test_timescaledb.sh -V -v -v -v -tsv $TSVERSION -pgv $PGVERSION --location ~/build/LloydAlbin
      after_script:
        #- bash <(curl -s https://codecov.io/bash)>
        - kubectl get all
        - kubectl get secrets
    - #stage: PostgreSQL 11
      name: "PostgreSQL 11 - TimescaleDB 1.5.1"
      env:
        - TSVERSION=1.5.1
        - PGVERSION=pg11
      language: bash
      services: docker
      sudo: required
      addons:
        apt:
          packages:
            - postgresql-client
            - perl
            - python3
            - python3-psycopg2
            - python3-daemon
      before_script:
        # Download kubectl, which is a requirement for using minikube.
        - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/$KUBEVERSION/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
        # Download minikube.
        - curl -Lo minikube https://storage.googleapis.com/minikube/releases/$MINIKUBEVERSION/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
        #- curl -Lo minikube https://storage.googleapis.com/minikube/releases/$MINIKUBEVERSION/minikube-linux-amd64 && chmod +x minikube && sudo install minikube-linux-amd64 /usr/local/bin/minikub && minikube kubectl -- get po -A
        - mkdir -p $HOME/.kube $HOME/.minikube
        - touch $KUBECONFIG
        - sudo minikube start --vm-driver=none --kubernetes-version=$KUBEVERSION
        - "sudo chown -R travis: /home/travis/.minikube/"
        # Add https://metacpan.org/pod/TAP::Parser::SourceHandler::pgTAP for pg_prove
        - cpanm --sudo TAP::Parser::SourceHandler::pgTAP
      script: 
        - ~/build/LloydAlbin/pg_monitor/internal_testing/test_timescaledb.sh -V -v -v -v -tsv $TSVERSION -pgv $PGVERSION --location ~/build/LloydAlbin
      after_script:
        #- bash <(curl -s https://codecov.io/bash)>
        - kubectl get all
        - kubectl get secrets
    - #stage: PostgreSQL 10
      name: "PostgreSQL 10 - TimescaleDB 1.6.1"
      env:
        - TSVERSION=1.6.1
        - PGVERSION=pg10
      language: bash
      services: docker
      sudo: required
      addons:
        apt:
          packages:
            - postgresql-client
            - perl
            - python3
            - python3-psycopg2
            - python3-daemon
      before_script:
        # Download kubectl, which is a requirement for using minikube.
        - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/$KUBEVERSION/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
        # Download minikube.
        - curl -Lo minikube https://storage.googleapis.com/minikube/releases/$MINIKUBEVERSION/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
        #- curl -Lo minikube https://storage.googleapis.com/minikube/releases/$MINIKUBEVERSION/minikube-linux-amd64 && chmod +x minikube && sudo install minikube-linux-amd64 /usr/local/bin/minikub && minikube kubectl -- get po -A
        - mkdir -p $HOME/.kube $HOME/.minikube
        - touch $KUBECONFIG
        - sudo minikube start --vm-driver=none --kubernetes-version=$KUBEVERSION
        - "sudo chown -R travis: /home/travis/.minikube/"
        # Add https://metacpan.org/pod/TAP::Parser::SourceHandler::pgTAP for pg_prove
        - cpanm --sudo TAP::Parser::SourceHandler::pgTAP
      script: 
        - ~/build/LloydAlbin/pg_monitor/internal_testing/test_timescaledb.sh -V -v -v -v -tsv $TSVERSION -pgv $PGVERSION --location ~/build/LloydAlbin
      after_script:
        #- bash <(curl -s https://codecov.io/bash)>
        - kubectl get all
        - kubectl get secrets
    - #stage: PostgreSQL 11
      name: "PostgreSQL 11 - TimescaleDB 1.6.1"
      env:
        - TSVERSION=1.6.1
        - PGVERSION=pg11
      language: bash
      services: docker
      sudo: required
      addons:
        apt:
          packages:
            - postgresql-client
            - perl
            - python3
            - python3-psycopg2
            - python3-daemon
      before_script:
        # Download kubectl, which is a requirement for using minikube.
        - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/$KUBEVERSION/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
        # Download minikube.
        - curl -Lo minikube https://storage.googleapis.com/minikube/releases/$MINIKUBEVERSION/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
        #- curl -Lo minikube https://storage.googleapis.com/minikube/releases/$MINIKUBEVERSION/minikube-linux-amd64 && chmod +x minikube && sudo install minikube-linux-amd64 /usr/local/bin/minikub && minikube kubectl -- get po -A
        - mkdir -p $HOME/.kube $HOME/.minikube
        - touch $KUBECONFIG
        - sudo minikube start --vm-driver=none --kubernetes-version=$KUBEVERSION
        - "sudo chown -R travis: /home/travis/.minikube/"
        # Add https://metacpan.org/pod/TAP::Parser::SourceHandler::pgTAP for pg_prove
        - cpanm --sudo TAP::Parser::SourceHandler::pgTAP
      script: 
        - ~/build/LloydAlbin/pg_monitor/internal_testing/test_timescaledb.sh -V -v -v -v -tsv $TSVERSION -pgv $PGVERSION --location ~/build/LloydAlbin
      after_script:
        #- bash <(curl -s https://codecov.io/bash)>
        - kubectl get all
        - kubectl get secrets
    - #stage: PostgreSQL 10
      name: "PostgreSQL 10 - TimescaleDB 1.7.4"
      env:
        - TSVERSION=1.7.4
        - PGVERSION=pg10
      language: bash
      services: docker
      sudo: required
      addons:
        apt:
          packages:
            - postgresql-client
            - perl
            - python3
            - python3-psycopg2
            - python3-daemon
      before_script:
        # Download kubectl, which is a requirement for using minikube.
        - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/$KUBEVERSION/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
        # Download minikube.
        - curl -Lo minikube https://storage.googleapis.com/minikube/releases/$MINIKUBEVERSION/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
        #- curl -Lo minikube https://storage.googleapis.com/minikube/releases/$MINIKUBEVERSION/minikube-linux-amd64 && chmod +x minikube && sudo install minikube-linux-amd64 /usr/local/bin/minikub && minikube kubectl -- get po -A
        - mkdir -p $HOME/.kube $HOME/.minikube
        - touch $KUBECONFIG
        - sudo minikube start --vm-driver=none --kubernetes-version=$KUBEVERSION
        - "sudo chown -R travis: /home/travis/.minikube/"
        # Add https://metacpan.org/pod/TAP::Parser::SourceHandler::pgTAP for pg_prove
        - cpanm --sudo TAP::Parser::SourceHandler::pgTAP
      script: 
        - ~/build/LloydAlbin/pg_monitor/internal_testing/test_timescaledb.sh -V -v -v -v -tsv $TSVERSION -pgv $PGVERSION --location ~/build/LloydAlbin
      after_script:
        #- bash <(curl -s https://codecov.io/bash)>
        - kubectl get all
        - kubectl get secrets
    - #stage: PostgreSQL 11
      name: "PostgreSQL 11 - TimescaleDB 1.7.4"
      env:
        - TSVERSION=1.7.4
        - PGVERSION=pg11
      language: bash
      services: docker
      sudo: required
      addons:
        apt:
          packages:
            - postgresql-client
            - perl
            - python3
            - python3-psycopg2
            - python3-daemon
      before_script:
        # Download kubectl, which is a requirement for using minikube.
        - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/$KUBEVERSION/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
        # Download minikube.
        - curl -Lo minikube https://storage.googleapis.com/minikube/releases/$MINIKUBEVERSION/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
        #- curl -Lo minikube https://storage.googleapis.com/minikube/releases/$MINIKUBEVERSION/minikube-linux-amd64 && chmod +x minikube && sudo install minikube-linux-amd64 /usr/local/bin/minikub && minikube kubectl -- get po -A
        - mkdir -p $HOME/.kube $HOME/.minikube
        - touch $KUBECONFIG
        - sudo minikube start --vm-driver=none --kubernetes-version=$KUBEVERSION
        - "sudo chown -R travis: /home/travis/.minikube/"
        # Add https://metacpan.org/pod/TAP::Parser::SourceHandler::pgTAP for pg_prove
        - cpanm --sudo TAP::Parser::SourceHandler::pgTAP
      script: 
        - ~/build/LloydAlbin/pg_monitor/internal_testing/test_timescaledb.sh -V -v -v -v -tsv $TSVERSION -pgv $PGVERSION --location ~/build/LloydAlbin
      after_script:
        #- bash <(curl -s https://codecov.io/bash)>
        - kubectl get all
        - kubectl get secrets
    - # stage: PostgreSQl 12
      name: "PostgreSQL 12 - TimescaleDB 1.7.4"
      env:
        - TSVERSION=1.7.4
        - PGVERSION=pg12
      language: bash
      services: docker
      sudo: required
      addons:
        apt:
          packages:
            - postgresql-client
            - perl
            - python3
            - python3-psycopg2
            - python3-daemon
      before_script:
        # Download kubectl, which is a requirement for using minikube.
        - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/$KUBEVERSION/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
        # Download minikube.
        - curl -Lo minikube https://storage.googleapis.com/minikube/releases/$MINIKUBEVERSION/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
        #- curl -Lo minikube https://storage.googleapis.com/minikube/releases/$MINIKUBEVERSION/minikube-linux-amd64 && chmod +x minikube && sudo install minikube-linux-amd64 /usr/local/bin/minikub && minikube kubectl -- get po -A
        - mkdir -p $HOME/.kube $HOME/.minikube
        - touch $KUBECONFIG
        - sudo minikube start --vm-driver=none --kubernetes-version=$KUBEVERSION
        - "sudo chown -R travis: /home/travis/.minikube/"
        # Add https://metacpan.org/pod/TAP::Parser::SourceHandler::pgTAP for pg_prove
        - cpanm --sudo TAP::Parser::SourceHandler::pgTAP
      script: 
        - ~/build/LloydAlbin/pg_monitor/internal_testing/test_timescaledb.sh -V -v -v -v -tsv $TSVERSION -pgv $PGVERSION --location ~/build/LloydAlbin
      after_script:
        #- bash <(curl -s https://codecov.io/bash)>
        - kubectl get all
        - kubectl get secrets
    - #stage: PostgreSQL 11
      name: "PostgreSQL 11 - TimescaleDB (latest)"
      env:
        - TSVERSION=latest
        - PGVERSION=pg11
      language: bash
      services: docker
      sudo: required
      addons:
        apt:
          packages:
            - postgresql-client
            - perl
            - python3
            - python3-psycopg2
            - python3-daemon
      before_script:
        # Download kubectl, which is a requirement for using minikube.
        - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/$KUBEVERSION/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
        # Download minikube.
        - curl -Lo minikube https://storage.googleapis.com/minikube/releases/$MINIKUBEVERSION/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
        #- curl -Lo minikube https://storage.googleapis.com/minikube/releases/$MINIKUBEVERSION/minikube-linux-amd64 && chmod +x minikube && sudo install minikube-linux-amd64 /usr/local/bin/minikub && minikube kubectl -- get po -A
        - mkdir -p $HOME/.kube $HOME/.minikube
        - touch $KUBECONFIG
        - sudo minikube start --vm-driver=none --kubernetes-version=$KUBEVERSION
        - "sudo chown -R travis: /home/travis/.minikube/"
        # Add https://metacpan.org/pod/TAP::Parser::SourceHandler::pgTAP for pg_prove
        - cpanm --sudo TAP::Parser::SourceHandler::pgTAP
      script: 
        - ~/build/LloydAlbin/pg_monitor/internal_testing/test_timescaledb.sh -V -v -v -v -tsv $TSVERSION -pgv $PGVERSION --location ~/build/LloydAlbin
      after_script:
        #- bash <(curl -s https://codecov.io/bash)>
        - kubectl get all
        - kubectl get secrets
    - # stage: PostgreSQl 12
      name: "PostgreSQL 12 - TimescaleDB (latest)"
      env:
        - TSVERSION=latest
        - PGVERSION=pg12
      language: bash
      services: docker
      sudo: required
      addons:
        apt:
          packages:
            - postgresql-client
            - perl
            - python3
            - python3-psycopg2
            - python3-daemon
      before_script:
        # Download kubectl, which is a requirement for using minikube.
        - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/$KUBEVERSION/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
        # Download minikube.
        - curl -Lo minikube https://storage.googleapis.com/minikube/releases/$MINIKUBEVERSION/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
        #- curl -Lo minikube https://storage.googleapis.com/minikube/releases/$MINIKUBEVERSION/minikube-linux-amd64 && chmod +x minikube && sudo install minikube-linux-amd64 /usr/local/bin/minikub && minikube kubectl -- get po -A
        - mkdir -p $HOME/.kube $HOME/.minikube
        - touch $KUBECONFIG
        - sudo minikube start --vm-driver=none --kubernetes-version=$KUBEVERSION
        - "sudo chown -R travis: /home/travis/.minikube/"
        # Add https://metacpan.org/pod/TAP::Parser::SourceHandler::pgTAP for pg_prove
        - cpanm --sudo TAP::Parser::SourceHandler::pgTAP
      script: 
        - ~/build/LloydAlbin/pg_monitor/internal_testing/test_timescaledb.sh -V -v -v -v -tsv $TSVERSION -pgv $PGVERSION --location ~/build/LloydAlbin
      after_script:
        #- bash <(curl -s https://codecov.io/bash)>
        - kubectl get all
        - kubectl get secrets
