apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pg-monitor-timescaledb
  name: pg-monitor-timescaledb
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pg-monitor-timescaledb
  template:
    metadata:
      labels:
        app: pg-monitor-timescaledb
      name: pg-monitor-timescaledb
    spec:
      containers:
      - env:
        - name: PGDATA
          value: /pgdata_local/11
        - name: POSTGRES_INITDB_ARGS
          value: --data-checksums --encoding=UTF8 --locale=en_US --auth-host='md5'
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-monitor-timescaledb-pg-pass
              key: password
#          value: pgpass
        image: lloydalbin/timescaledb:2.0.0-rc2-pg12
        imagePullPolicy: IfNotPresent
        name: pg-monitor-timescaledb
        ports:
        - containerPort: 5432
          protocol: TCP
        volumeMounts:
          - name: podinfo
          mountPath: /etc/podinfo
#        - mountPath: /pgdata_local
#          name: netapp
#        resources:
#          requests:
#            memory: "8G"
#            cpu: 4
#          limits:
#            memory: "8G"
#            cpu: 4
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
# https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/          
        - name: podinfo
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations
#      - name: netapp
#        persistentVolumeClaim:
#          claimName: pg-monitor-timescaledb
