{
 "title": "AutoVacuum Log",
 "tags": [
  "AutoVacuum",
  "AutoAnalyze",
  "PG Logs"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ServerName",
    "label": "Server Name",
    "query": "SELECT DISTINCT cluster_name FROM reports.postgres_log_databases"
   },
   {
    "name": "DatabaseName",
    "label": "Database Name",
    "query": "SELECT DISTINCT database_name FROM reports.postgres_log_databases WHERE cluster_name IN ($ServerName) UNION SELECT DISTINCT database_name FROM reports.autovacuum_logs WHERE cluster_name IN ($ServerName)"
   },
   {
    "name": "SchemaName",
    "label": "Schema Name",
    "query": "SELECT DISTINCT schema_name FROM reports.autovacuum_logs  WHERE  $__timeFilter(time)     AND cluster_name IN ($ServerName)     AND database_name IN ($DatabaseName) UNION SELECT DISTINCT schema_name FROM reports.autoanalyze_logs  WHERE  $__timeFilter(time)     AND cluster_name IN ($ServerName)     AND database_name IN ($DatabaseName)"
   },
   {
    "name": "TableName",
    "label": "Table Name",
    "query": "SELECT DISTINCT table_name FROM reports.autovacuum_logs  WHERE $__timeFilter(time)     AND cluster_name IN ($ServerName)     AND database_name IN ($DatabaseName)     AND schema_name IN ($SchemaName) UNION SELECT DISTINCT table_name FROM reports.autoanalyze_logs  WHERE $__timeFilter(time)     AND cluster_name IN ($ServerName)     AND database_name IN ($DatabaseName)     AND schema_name IN ($SchemaName)"
   },
   { "name": "QueryLimit", "label": "Query Limit", "query": "100000" },
   {
    "name": "GraphInterval",
    "label": "Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "AutoVacuum",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SET application_name TO 'Grafana';\nSELECT * FROM reports.autovacuum_log_count_chart($$$__timeFilter(time)$$, $$$ServerName$$, $$$DatabaseName$$, $$$SchemaName$$, $$$TableName$$);\n/* -- Original working Query\nSELECT now() AS time, cluster_name || '.' || database_name || '.' || schema_name || '.' || table_name, count(*) AS count\nFROM reports.autovacuum_log($$$__timeFilter(time)$$, $$$ServerName$$, $$$DatabaseName$$, $$$SchemaName$$, $$$TableName$$, $QueryLimit)\nGROUP BY cluster_name || '.' || database_name || '.' || schema_name || '.' || table_name\nORDER BY 3 DESC, 2 ASC;\n*/",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "AutoAnalyze",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SET application_name TO 'Grafana';\nSELECT * FROM reports.autoanalyze_log_count_chart($$$__timeFilter(time)$$, $$$ServerName$$, $$$DatabaseName$$, $$$SchemaName$$, $$$TableName$$);\n/*\nSELECT now() AS time, cluster_name || '.' || database_name || '.' || schema_name || '.' || table_name, count(*) AS count\nFROM reports.autoanalyze_log($$$__timeFilter(time)$$, $$$ServerName$$, $$$DatabaseName$$, $$$SchemaName$$, $$$TableName$$, $QueryLimit)\nGROUP BY cluster_name || '.' || database_name || '.' || schema_name || '.' || table_name\nORDER BY 3 DESC, 2 ASC;\n*/\n",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Tuples Removed",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SET application_name = 'Grafana';\nSELECT * FROM reports.autovacuum_log_tuples_removed_chart($$$__timeFilter(time)$$, $$$ServerName$$, $$$DatabaseName$$, $$$SchemaName$$, $$$TableName$$);\n",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Recovered Space",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SET application_name = 'Grafana';\nSELECT * FROM reports.autovacuum_log_removed_space_chart($$$__timeFilter(time)$$, $$$ServerName$$, $$$DatabaseName$$, $$$SchemaName$$, $$$TableName$$);\n",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "AutoVacuum's / AutoAnalyze's - $GraphInterval Interval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SET application_name = 'Grafana';\nSELECT time, cluster_name || ' - vacuum', count FROM reports.autovacuum_log_count('$GraphInterval', $$$__timeFilter(time)$$, $__timeFrom(), $__timeTo(), $$$ServerName$$, $$$DatabaseName$$, $$$SchemaName$$, $$$TableName$$);"
    },
    {
     "rawSql": "SET application_name = 'Grafana';\nSELECT time, cluster_name || ' - analyze', count FROM reports.autoanalyze_log_count('$GraphInterval', $$$__timeFilter(time)$$, $__timeFrom(), $__timeTo(), $$$ServerName$$, $$$DatabaseName$$, $$$SchemaName$$, $$$TableName$$);"
    }
   ]
  },
  {
   "title": "AutoVacuum Tuples Removed - $GraphInterval Interval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SET application_name = 'Grafana';\nSELECT * FROM reports.autovacuum_log_tuples_removed('$GraphInterval', $$$__timeFilter(time)$$, $$$ServerName$$, $$$DatabaseName$$, $$$SchemaName$$, $$$TableName$$);"
    }
   ]
  },
  {
   "title": "AutoVacuum Recovered Space - $GraphInterval Interval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "rawSql": "SET application_name = 'Grafana';\nSELECT * FROM reports.autovacuum_log_removed_size('$GraphInterval', $$$__timeFilter(time)$$, $$$ServerName$$, $$$DatabaseName$$, $$$SchemaName$$, $$$TableName$$);\n/*SELECT time_bucket('$__interval',time) AS \"time\",\n   cluster_name,\n  sum(removed_size) AS removed_size\nFROM\n  reports.auto_vacuum_logs\nWHERE cluster_name IN ($ServerName)  \nGROUP BY time_bucket('$__interval',time), cluster_name\nORDER BY time, cluster_name*/"
    }
   ]
  },
  {
   "title": "Test graph for table size after autovacuum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "rawSql": "SET application_name TO 'Grafana';\nSELECT time, cluster_name || '.' || database_name || '.' || schema_name || '.' || table_name, pages_remain_size FROM reports.autovacuum_log($$$__timeFilter(time)$$, $$$ServerName$$, $$$DatabaseName$$, $$$SchemaName$$, $$$TableName$$, 100000000) ORDER BY time ASC;\n"
    }
   ]
  },
  {
   "title": "Last $QueryLimit Auto-Vacuum's",
   "type": "table",
   "gridPos": { "h": 28, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "rawSql": "SET application_name TO 'Grafana';\nSELECT * FROM reports.autovacuum_log($$$__timeFilter(time)$$, $$$ServerName$$, $$$DatabaseName$$, $$$SchemaName$$, $$$TableName$$, $QueryLimit);"
    }
   ]
  },
  {
   "title": "Last $QueryLimit Auto-Analyze's",
   "type": "table",
   "gridPos": { "h": 27, "w": 17, "x": 0, "y": 69 },
   "targets": [
    {
     "rawSql": "SET application_name TO 'Grafana';\nSELECT * FROM reports.autoanalyze_log($$$__timeFilter(time)$$, $$$ServerName$$, $$$DatabaseName$$, $$$SchemaName$$, $$$TableName$$, $QueryLimit);"
    }
   ]
  },
  {
   "title": "AutoVacuum Activity",
   "type": "table",
   "gridPos": { "h": 27, "w": 7, "x": 17, "y": 69 },
   "targets": [
    {
     "rawSql": "SET application_name TO 'Grafana';\nSELECT * FROM reports.autovacuum_autoanalyze_count($$$__timeFilter(time)$$, $$$ServerName$$, $$$DatabaseName$$, $$$SchemaName$$, $$$TableName$$);"
    }
   ]
  }
 ]
}