{
 "title": "Checkpoint Logs",
 "tags": [
  "Checkpoint",
  "PG Logs"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ServerName",
    "label": "Server Name",
    "query": "SELECT DISTINCT cluster_name FROM reports.postgres_log_databases"
   },
   { "name": "QueryLimit", "label": "Query Limit", "query": "100000" },
   {
    "name": "GraphInterval",
    "label": "Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Checkpoint Write Buffers - $GraphInterval Interval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SET application_name TO 'Grafana';\nSELECT * FROM reports.checkpoint_write_buffers('$GraphInterval', $$$__timeFilter(time)$$, $__timeFrom(), $__timeTo(), $$$ServerName$$);\n"
    }
   ]
  },
  {
   "title": "Checkpoint WAL File Usage - $GraphInterval Interval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SET application_name TO 'Grafana';\nSELECT * FROM reports.checkpoint_wal_file_usage('$GraphInterval', $$$__timeFilter(time)$$, $__timeFrom(), $__timeTo(), $$$ServerName$$);\n"
    }
   ]
  },
  {
   "title": "Checkpoint Buffers",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SET application_name TO 'Grafana';\nSELECT * FROM reports.checkpoint_buffers('1 hour', $$$__timeFilter(time)$$, $__timeFrom(), $__timeTo(), $$$ServerName$$);"
    }
   ]
  },
  {
   "title": "Checkpoint Files",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "rawSql": "SET application_name TO 'Grafana';\nSELECT * FROM reports.checkpoint_files('1 hour', $$$__timeFilter(time)$$, $__timeFrom(), $__timeTo(), $$$ServerName$$);"
    }
   ]
  },
  {
   "title": "Checkpoint Logs",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "rawSql": "SET application_name TO 'Grafana';\nSELECT * FROM reports.checkpoint_logs($$$__timeFilter(time)$$, $$$ServerName$$, $QueryLimit);"
    }
   ]
  },
  {
   "title": "Checkpoint Warnings - $GraphInterval Interval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SET application_name TO 'Grafana';\nSELECT * FROM reports.checkpoint_warning_logs_count('$GraphInterval', $$$__timeFilter(time)$$, $__timeFrom(), $__timeTo(), $$$ServerName$$);\n"
    }
   ]
  },
  {
   "title": "Checkpoint Warnings",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "rawSql": "SET application_name TO 'Grafana';\nSELECT * FROM reports.checkpoint_warning_logs($$$__timeFilter(time)$$, $$$ServerName$$, $QueryLimit);"
    }
   ]
  }
 ]
}