{
 "title": "LDAP Errors",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ServerName",
    "query": "SELECT DISTINCT cluster_name FROM reports.postgres_log WHERE $__timeFilter(log_time)"
   }
  ]
 },
 "panels": [
  {
   "title": "LDAP Errors Per Minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SET application_name = 'Grafana';\nSELECT * FROM reports.ldap_error_history('$__interval', $$$__timeFilter(log_time)$$, ARRAY[$ServerName]::text[], 'minute', 'sum', False);\n\n/*\nSELECT c.start_time AS time, c.ldap_error, COALESCE(e.value,0) AS value1 \nFROM (\n\tSELECT a.*, b.* \n\tFROM tools.generate_timestamps('$__interval', $$$__timeFilter(log_time)$$) a,\n\t(\n    \tSELECT \n    \t\tCASE WHEN 'All' = $ServerName THEN cluster_name || ' - ' ELSE '' END || trim(split_part(message, ':', 2)) AS ldap_error \n\t\tFROM reports.postgres_log \n\t\tWHERE message LIKE 'LDAP login failed for user%' AND $__timeFilter(log_time)\n\t\tGROUP BY 1\n     ) b\n) c LEFT JOIN (\n\tSELECT * FROM (\n\t\tSELECT  \n\t\t\tdate_trunc(tools.interval_to_field('$__interval'), log_time) AS time, \n\t\t\tCASE WHEN 'All' = $ServerName THEN cluster_name || ' - ' ELSE '' END || trim(split_part(message, ':', 2)) AS ldap_error, \n\t\t\tcount(*) AS value\n\t\tFROM reports.postgres_log \n  \t\tWHERE (cluster_name = $ServerName OR 'All' = $ServerName) AND message LIKE 'LDAP login failed for user%' \n  \t\tGROUP BY 1,2\n\t) d WHERE $__timeFilter(time)\n) e ON c.start_time = e.time AND c.ldap_error = e.ldap_error;\n*/"
    }
   ]
  },
  {
   "title": "Connection Attempts Per Second (Each requiring Authentication via LDAP)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SET application_name = 'Grafana';\nSELECT * FROM reports.connection_attempt_history('$__interval'::text, $$$__timeFilter(log_time)$$::text, ARRAY[$ServerName]::text[], 'second'::text, 'max'::text, False);"
    }
   ]
  },
  {
   "title": "Connections Per Second (Requiring Authentication via LDAP)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SET application_name = 'Grafana';\nSELECT * FROM reports.connection_history('$__interval'::text, $$$__timeFilter(log_time)$$::text, ARRAY[$ServerName]::text[], 'second'::text, 'max'::text, False);"
    }
   ]
  },
  {
   "title": "LDAP Errors by User",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "SET application_name = 'Grafana';  \n    SELECT \n    cluster_name,\n    CASE WHEN message LIKE E'%Can''t contact LDAP server' THEN trim(split_part(message, '\"', 1)) ELSE trim(split_part(message, ':', 2)) END AS ldap_error,\n    user_name,\n    count(*) AS value\n  FROM reports.postgres_log \n  WHERE ARRAY[cluster_name] <@ ARRAY[$ServerName] AND (message LIKE 'LDAP login failed for user%' OR message LIKE E'%Can''t contact LDAP server') AND $__timeFilter(log_time)\n  GROUP BY 1,2,3;"
    }
   ]
  },
  {
   "title": "Postgres Error's",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "rawSql": "SET application_name = 'Grafana';  \nSELECT cluster_name, message, count(*) AS value \nFROM reports.postgres_log \nWHERE ARRAY[cluster_name] <@ ARRAY[$ServerName] AND error_severity = 'ERROR' AND $__timeFilter(log_time)\nGROUP BY 1,2; \n"
    }
   ]
  },
  {
   "title": "Postgres Fatal Error's",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "rawSql": "SET application_name = 'Grafana';  \nSELECT cluster_name, message, count(*) AS value \nFROM reports.postgres_log \nWHERE ARRAY[cluster_name] <@ ARRAY[$ServerName] AND error_severity = 'FATAL' AND $__timeFilter(log_time)\nGROUP BY 1,2; \n"
    }
   ]
  }
 ]
}