{
 "title": "Locks Log",
 "tags": [
  "Locks",
  "PG Logs"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ServerName",
    "label": "Server Name",
    "query": "SELECT DISTINCT cluster_name FROM reports.postgres_log_databases"
   },
   {
    "name": "DatabaseName",
    "label": "Database Name",
    "query": "SELECT DISTINCT database_name FROM reports.postgres_log_databases WHERE cluster_name IN ($ServerName)"
   },
   { "name": "QueryLimit", "label": "Query Limit", "query": "100" }
  ]
 },
 "panels": [
  {
   "title": "Locks by Types",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SET application_name = 'Grafana';\nSELECT \n\tlock_type, object_type,\n    count(*) AS count, \n    sum(wait_time::NUMERIC) as total_duration, \n    avg(wait_time::NUMERIC) as average_duration, \n    min(wait_time::NUMERIC) as min_duration, \n    max(wait_time::NUMERIC) as max_duration \nFROM reports.lock_logs\nWHERE (cluster_name IN ($ServerName) OR $$$ServerName$$ = 'NULL')\n  AND (database_name IN ($DatabaseName) OR $$$DatabaseName$$ = 'NULL')\n  AND $__timeFilter(time)\nGROUP BY ROLLUP(lock_type, object_type)\nORDER BY 1 NULLS LAST,2 NULLS LAST;"
    }
   ]
  },
  {
   "title": "Most frequent waiting queries ($QueryLimit)",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SET application_name = 'Grafana';\nSELECT\n\tcluster_name, database_name, query,\n    count(*) AS count, \n    sum(wait_time::NUMERIC) as total_duration, \n    avg(wait_time::NUMERIC) as average_duration, \n    min(wait_time::NUMERIC) as min_duration, \n    max(wait_time::NUMERIC) as max_duration \nFROM reports.lock_logs\nWHERE (cluster_name IN ($ServerName) OR $$$ServerName$$ = 'NULL')\n  AND (database_name IN ($DatabaseName) OR $$$DatabaseName$$ = 'NULL')\n  AND $__timeFilter(time)\nGROUP BY cluster_name, database_name, query\nORDER BY 5 DESC\nLIMIT $QueryLimit;"
    }
   ]
  },
  {
   "title": "Queries that waited the most ($QueryLimit)",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "SET application_name = 'Grafana';\nSELECT\n    time,\n    cluster_name,\n    database_name,\n    user_name,\n    wait_time::NUMERIC,\n    trim(query) AS query\nFROM reports.lock_logs\nWHERE (cluster_name IN ($ServerName) OR $$$ServerName$$ = 'NULL')\n  AND (database_name IN ($DatabaseName) OR $$$DatabaseName$$ = 'NULL')\n  AND $__timeFilter(time)\nORDER BY wait_time DESC\nLIMIT $QueryLimit;"
    }
   ]
  }
 ]
}