apiVersion: v1
kind: Service
metadata:
  name: pg-monitor-grafana
  labels:
    app: pg-monitor-grafana
spec:
  ports:
  - nodePort: 30000
    port: 3000
    targetPort: 3000
    protocol: TCP
    name: pg-monitor-grafana
  selector:
    app: pg-monitor-grafana
  type: NodePort
