apiVersion: v1
kind: Pod
metadata:
  name: pg-monitor-grafana-pod-inspector
  namespace: ifs
spec:
  containers:
  - env:
    - name: GF_DEFAULT_APP_MODE
      value: development
    image: ubuntu
    imagePullPolicy: IfNotPresent
    name: pg-monitor-grafana-pod-inspector
    command: [ "/bin/bash", "-c", "--" ]
    args:
    - apt-get update;
      apt-get upgrade;
      mkdir -p /netapp2;
      while true; 
      do sleep 30; 
      done;
    ports:
    - containerPort: 3000
      protocol: TCP
    volumeMounts:
    - mountPath: /netapp
      name: netapp
    securityContext:
      allowPrivilegeEscalation: true
  restartPolicy: Always
  volumes:
  - name: netapp
    persistentVolumeClaim:
      claimName: pg-monitor-grafana
