apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-monitor-grafana
  annotations:
    trident.netapp.io/reclaimPolicy: "Retain"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
